// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXSHKxGcStF3H1gJ9_8aXtRQiNIoH4nAw',
    appId: '1:856668204005:web:eefea432336158833a1d0c',
    messagingSenderId: '856668204005',
    projectId: 'billnews-c5913',
    authDomain: 'billnews-c5913.firebaseapp.com',
    storageBucket: 'billnews-c5913.appspot.com',
    measurementId: 'G-556NN177E3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkzGmuxNKInvG-X1gWt3H1Rv1kg8cH7iI',
    appId: '1:856668204005:android:799cfbc270043c0d3a1d0c',
    messagingSenderId: '856668204005',
    projectId: 'billnews-c5913',
    storageBucket: 'billnews-c5913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyUVqoMavQGQprMw367X0EM8e6GIUbrEE',
    appId: '1:856668204005:ios:d7930766e83737003a1d0c',
    messagingSenderId: '856668204005',
    projectId: 'billnews-c5913',
    storageBucket: 'billnews-c5913.appspot.com',
    iosClientId: '856668204005-og3ijc6ld5ot1jc1r28131vbps3vo2e3.apps.googleusercontent.com',
    iosBundleId: 'mrblab.newshourapp',
  );
}
